### ISSUE TITLE
Connection fails on linux

### ISSUE THREAD

**Issue by Kilill** [python-postgres/fe#101]
Ubuntu 16.04.6 LTS
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import postgresql
>>> db= postgresql.open("pq://localhost/weather")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/div/work/weather/db/py/fe/postgresql/__init__.py", line 92, in open
    c.connect()
  File "/home/div/work/weather/db/py/fe/postgresql/driver/pq3.py", line 2427, in connect
    self._establish()
  File "/home/div/work/weather/db/py/fe/postgresql/driver/pq3.py", line 2559, in _establish
    self.version_info = pg_version.normalize(pg_version.split(sv))
  File "/home/div/work/weather/db/py/fe/postgresql/versionstring.py", line 28, in split
    vlist = [int(x or '0') for x in v[:-1]]
  File "/home/div/work/weather/db/py/fe/postgresql/versionstring.py", line 28, in <listcomp>
    vlist = [int(x or '0') for x in v[:-1]]
ValueError: invalid literal for int() with base 10: '2 (Ubuntu 11'

**Comment by jwp** [comment]
The debian and ubuntu PostgreSQL packages ship with a modified postgresql version string. I would recommend using a different PostgreSQL package, install from source, or use debian's py-postgresql package accommodating for the modification local to their distribution.

**Comment by pensnarik** [comment]
Is it possible to adopt is so as the module could be used with any version string? It's ridiculous that I cannot use it only because of this.
