### ISSUE TITLE
Connector throwing AuthenticationMethodError

### ISSUE THREAD

**Issue by geoffwinans** [python-postgres/fe#117]
```
Traceback (most recent call last):
  File "dbtest.py", line 3, in <module>
    db = postgresql.open("pq://postgres:mysecretpassword@127.0.0.1:5432/postgres")
  File "/home/gw/.local/lib/python3.6/site-packages/postgresql/__init__.py", line 92, in open
    c.connect()
  File "/home/gw/.local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2427, in connect
    self._establish()
  File "/home/gw/.local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 2553, in _establish
    self.typio.raise_client_error(could_not_connect, creator = self, cause = exc)
  File "/home/gw/.local/lib/python3.6/site-packages/postgresql/driver/pq3.py", line 514, in raise_client_error
    raise client_error
postgresql.exceptions.ClientCannotConnectError: could not establish connection to server
  CODE: 08001
  LOCATION: CLIENT
CONNECTION: [failed]
  failures[0]:
    NOSSL socket('127.0.0.1', 5432)
    postgresql.exceptions.AuthenticationMethodError: unsupported authentication request '<unknown>'(10)
      CODE: --AUT
      LOCATION: CLIENT
      HINT: 'postgresql.protocol' only supports: MD5, crypt, plaintext, and trust.
CONNECTOR: [IP4] pq://postgres:***@127.0.0.1:5432/postgres
  category: None
DRIVER: postgresql.driver.pq3.Driver
```

----

```
gw@testhost:~$ cat dbtest.py 
import postgresql

db = postgresql.open("pq://postgres:mysecretpassword@127.0.0.1:5432/postgres")
```

----

I'm at a loss as to what else to do here. I am attempting to connect to a postgres 10.x docker container.

Of note, I can connect using psql without issue.

I tried using the server_encoding hint, but I truly have no idea how to *use* it.

**Comment by jwp** [comment]
Looks like the server is configured to prefer SASL SCRAM. You'll have to use MD5, plaintext, or trust to get the client to connect.
