### ISSUE TITLE
Collections has no attribute 'Iterator'

### ISSUE THREAD

**Issue by GuyARoss** [python-postgres/fe#120]
After doing a fresh install, I ran a test script and got the following error.
```
Traceback (most recent call last):                                                                                       
  File "/home/ubuntu/betr/thing/main.py", line 182, in <module>                                                
    db = postgresql.open('__redacted__')                                                                                                                    
  File "/home/ubuntu/.local/lib/python3.10/site-packages/postgresql/__init__.py", line 61, in open
    from . import driver as _pg_driver                      
  File "/home/ubuntu/.local/lib/python3.10/site-packages/postgresql/driver/__init__.py", line 9, in <module>
    from .pq3 import Driver                                 
  File "/home/ubuntu/.local/lib/python3.10/site-packages/postgresql/driver/pq3.py", line 20, in <module>
    from .. import lib as pg_lib
  File "/home/ubuntu/.local/lib/python3.10/site-packages/postgresql/lib/__init__.py", line 20, in <module>
    from .. import api as pg_api
  File "/home/ubuntu/.local/lib/python3.10/site-packages/postgresql/api.py", line 207, in <module>
    collections.Iterator,
AttributeError: module 'collections' has no attribute 'Iterator'
```

Machine: Ubuntu Server, ARM Raspberry PI.

Is this package supported on ARM?

**Comment by jwp** [comment]
Looks like you're using an old version(of py-postgresql). `collections.Iterator` is the old location of collections.abc.Iterator.

**Comment by GuyARoss** [comment]
> Looks like you're using an old version(of py-postgresql). `collections.Iterator` is the old location of `collections.abc.Iterator`.

I ran this same version check on two different machines, one with a working version of this module and the other with the broken version. It appears that both are of the same version..

```
>>> from postgresql import version
>>> print(version)
1.2.2
```

**Comment by GuyARoss** [comment]
My fix was downgrading the latest version of python to 3.8.

**Comment by jwp** [comment]
Thought I pushed those changes out to a release. Latest master branch has the fixes for it.

**Comment by jwp** [comment]
Yeah, I'll get to it soon. I wanted to break compatibility with older Pythons, but I think that might be too far despite them being past EOL. The current 1.3 in master does this and needs adjustments to be friendly with old versions.

**Comment by jwp** [comment]
Correction, looks like it works back to (at least) 3.7 as-is, so I might just upload it today.

**Comment by davidweissSOC** [comment]
That'd be awesome, thanks!

**Comment by jwp** [comment]
Uploaded.
