### ISSUE TITLE
lib.net_pack stores wrong bit length

### ISSUE THREAD

**Issue by FirefighterBlu3** [python-postgres/fe#71]
when packing an ip_address() for io, the bits value is wrongly stored as a /0 instead of /32 or /128

the following will fix this:

```
--- /usr/lib/python3.4/site-packages/postgresql/types/io/lib.py.orig    2014-06-02 12:42:50.783337348 +0000
+++ /usr/lib/python3.4/site-packages/postgresql/types/io/lib.py 2014-06-02 12:56:30.460003975 +0000
@@ -283,7 +283,9 @@
        Pack Postgres' inet/cidr data structure.
        """
        family, mask, data = triple
-       return bytes((fmap[family], mask or 0, 0 if mask is None else 1, len(data))) + data
+       mflag = mask and 1 or 0
+       mask = mask and mask or {4:32, 6:128}[family]
+       return bytes((fmap[family], mask, mflag, len(data))) + data

 def net_unpack(data,
        # Map IP version number to PGSQL src/include/utils/inet.h.
```

the original code stores "1.2.3.4" as "1.2.3.4/0" instead of "1.2.3.4/32". the above fix will store the correct bits value

**Comment by FirefighterBlu3** [comment]
@commonism correct. for type INET you cannot have a mask length, mask length is only valid for type CIDR. 1.1.1.1/24. regardless, this patch is no longer needed with modern libpq as it does the needed cleanup -- no mask length is recorded in the inserted data value if is_cidr bit is not set and type is INET.

**Comment by commonism** [comment]
You are wrong with your assumption INET can not have a mask.

http://www.postgresql.org/docs/9.4/static/datatype-net-types.html

> 8.9.1. inet
> The inet type holds an IPv4 or IPv6 host address, and optionally its subnet, all in one field. The subnet is represented by the number of network address bits present in the host address (the "netmask"). If the netmask is 32 and the address is IPv4, then the value does not indicate a subnet, only a single host. In IPv6, the address length is 128 bits, so 128 bits specify a unique host address.  Note that if you want to accept only networks, you should use the cidr type rather than inet.
> 
> The input format for this type is address/y where address is an IPv4 or IPv6 address and y is the number of bits in the netmask. If the /y portion is missing, the netmask is 32 for IPv4 and 128 for IPv6, so the value represents just a single host. On display, the /y portion is suppressed if the netmask specifies a single host.

INET allows a mask.

> 8.9.3. inet vs. cidr
> The essential difference between inet and cidr data types is that inet accepts values with nonzero bits to the right of the netmask, whereas cidr does not.

INET could be mapped to  IPvXInterface.
https://docs.python.org/3.5/library/ipaddress.html#ipaddress.IPv4Interface

**Comment by FirefighterBlu3** [comment]
My presentation was unclear, I apologize. For PostgreSQL type INET, you cannot have netmask bits set *when using ```ipaddress.ip_address()```.* ```ip_address()``` will reject the data if a bitmask is present, and ```ipaddress``` is the default translator for py-postgresql in Python3.

```python
>>> ipaddress.ip_address('1.1.1.1')
IPv4Address('1.1.1.1')
>>> ipaddress.ip_address('1.1.1.1/32')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/ipaddress.py", line 54, in ip_address
    address)
ValueError: '1.1.1.1/32' does not appear to be an IPv4 or IPv6 address
>>> ipaddress.ip_network('1.1.1.1/32')
IPv4Network('1.1.1.1/32')
```

```ipaddress.ip_network()``` can accept address data (and will translate) wherein the data appears to be a host but has a less than full width mask set.

```python
>>> ipaddress.ip_network('1.1.1.1/24')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/usr/lib64/python3.4/ipaddress.py", line 1490, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 1.1.1.1/24 has host bits set
>>> ipaddress.ip_network('1.1.1.1/24', strict=False)
IPv4Network('1.1.1.0/24')
```

Previous to my patch, py-postgresql was storing INET addresses with a netmask indicated as /0. PostgreSQL is happy storing this data with a mask length, but querying it results in exceptions in the form of:

```python
>>> ipaddress.ip_address('1.1.1.1/0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/ipaddress.py", line 54, in ip_address
    address)
ValueError: '1.1.1.1/0' does not appear to be an IPv4 or IPv6 address
```

It's fine if other software is capable of using pgsql type INET with netmask bits. py-postgresql's data type translator uses ```ipaddress``` in Python3 and the basic INSERT/SELECT out of the box, will break.

In the past I had a modified ```ipaddress``` module that handled the hosts with a netmask length but the notion of least surprise is that these functions should work out of the box without having to modify core modules.

**Comment by jwp** [comment]
I think I remember running into this. It was a little annoying having to strip out the /0 from ::text casts. Provide some tests with the patch and I'll apply it.
