### ISSUE TITLE
postgresql.exceptions.SyntaxError: syntax error at or near "$1"

### ISSUE THREAD

**Issue by d33tah** [python-postgres/fe#77]
Hello,

I tried to run `fe` as a Django backend. I copied my [modified psycopg2 Django backend][1], replaced `bpgsql` with `postgresql.driver.dbapi20`, then pulled Django 1.7 source code and in tests/test_sqlite.py, I pointed to the backend and set it up. After running `python3 ./runtests.py backends`, I got this:

```
Testing against Django installed in '/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django'
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 124, in connect
    self.init_connection_state()
  File "/usr/local/lib/python3.4/dist-packages/django_bpgsql/base.py", line 150, in init_connection_state
    cursor.execute(self.ops.set_time_zone_sql(), [tz])
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/dbapi20.py", line 271, in execute
    ps = self.database.prepare(sql)
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 2326, in prepare
    ps._fini()
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 1513, in _fini
    self.database._pq_complete()
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.SyntaxError: syntax error at or near "$1"
  CODE: 42601
  LOCATION: File 'scan.l', line 1053, in scanner_yyerror from SERVER
  POSITION: 15
STATEMENT: [parsing]
  LINE:
    SET TIME ZONE $1
                  ^ [line 1, character 15]
  statement_id: py:0x7f74405c79e8
  string: SET TIME ZONE $1
CONNECTION: [idle]
  client_address: ::1/128
  client_port: 40301
  version:
    PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 5.2.1-21) 5.2.1 20151003, 64-bit
CONNECTOR: [Host] pq://root@localhost:5432/postgres
  category: None
DRIVER: postgresql.driver.pq3.Driver

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./runtests.py", line 405, in <module>
    options.failfast, args)
  File "./runtests.py", line 247, in django_tests
    test_labels or get_installed(), extra_tests=extra_tests)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/test/runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/test/runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/test/runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST_SERIALIZE", True),
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/creation.py", line 359, in create_test_db
    self._create_test_db(verbosity, autoclobber)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/creation.py", line 452, in _create_test_db
    with self._nodb_connection.cursor() as cursor:
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 167, in cursor
    cursor = utils.CursorWrapper(self._cursor(), self)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 138, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 133, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.7-py3.4.egg/django/db/backends/__init__.py", line 124, in connect
    self.init_connection_state()
  File "/usr/local/lib/python3.4/dist-packages/django_bpgsql/base.py", line 150, in init_connection_state
    cursor.execute(self.ops.set_time_zone_sql(), [tz])
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/dbapi20.py", line 271, in execute
    ps = self.database.prepare(sql)
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 2326, in prepare
    ps._fini()
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 1513, in _fini
    self.database._pq_complete()
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 2604, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "/usr/local/lib/python3.4/dist-packages/postgresql/driver/pq3.py", line 532, in raise_server_error
    raise server_error
django.db.utils.ProgrammingError: syntax error at or near "$1"
```
[1]: https://github.com/d33tah/bpgsql/commit/29634fd291fdb6bd48131cb6c45ac60eb663cf51

**Comment by jwp** [comment]
Not all SQL statements (in PostgreSQL) accept protocol parameters. In this case, I believe you have to interpolate the parameter directly in the string. That is, you'll have to change:

  File "/usr/local/lib/python3.4/dist-packages/django_bpgsql/base.py", line 150, in init_connection_state
    cursor.execute(self.ops.set_time_zone_sql(), [tz])

Alternatively, you can ask PostgreSQL.org to support protocol parameters in those cases, but I have no idea if that would be welcome or not.
