### ISSUE TITLE
Problem under SQLObject

### ISSUE THREAD

**Issue by phdru** [python-postgres/fe#83]
The following code produces exception:

```python
from sqlobject import *

__connection__ = "postgres:/test?driver=pypostgresql&debug=1&debugOutput=1&charset=utf-8"

conn = connectionForURI(__connection__)

conn.query("""
CREATE TABLE person (
    id SERIAL PRIMARY KEY,
    name TEXT
)
""")

print(conn.queryOne("INSERT INTO person (name) VALUES ('Test') RETURNING id"))

Traceback (most recent call last):
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/dbapi20.py", line 92, in __next__
    r = self.buf[self.pos]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test1.py", line 21, in <module>
    print(conn.queryOne("INSERT INTO person (name) VALUES ('Test') RETURNING id"))
  File "/home/phd/tmp/test-SQLObject/sqlobject/dbconnection.py", line 482, in queryOne
    return self._runWithConnection(self._queryOne, s)
  File "/home/phd/tmp/test-SQLObject/sqlobject/dbconnection.py", line 348, in _runWithConnection
    val = meth(conn, *args)
  File "/home/phd/tmp/test-SQLObject/sqlobject/dbconnection.py", line 476, in _queryOne
    value = c.fetchone()
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/dbapi20.py", line 187, in fetchone
    return next(self._portal)
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/dbapi20.py", line 100, in __next__
    self.buf = next(self.chunks)
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 1009, in __next__
    self.database._pq_complete()
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 2609, in _pq_complete
    self.typio.raise_error(x.error_message, cause = getattr(x, 'exception', None))
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 541, in raise_error
    self.raise_server_error(error_message, **kw)
  File "/home/phd/.virtualenvs/pg8000-pypostgres/lib/python3.4/site-packages/postgresql/driver/pq3.py", line 532, in raise_server_error
    raise server_error
postgresql.exceptions.SyntaxError: syntax error at or near "INSERT"
  CODE: 42601
  LOCATION: File 'scan.l', line 1052, in scanner_yyerror from SERVER
  POSITION: 65
RESULT:
  chunksize: 4096
  type: MultiXactOutsideBlock
  parameters: ()
  cursor_id: py:0xb673066c
STATEMENT: [prepared]
  sql_parameter_types: []
  results: ('id' 'INTEGER')
  statement_id: py:0xb673084c
  string: INSERT INTO person (name) VALUES ('Test') RETURNING id
CONNECTION: [idle]
  client_port: -1
  version:
    PostgreSQL 9.4.9 on i686-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 32-bit
CONNECTOR: [Unix] pq://phd@[unix::var:run:postgresql:.s.PGSQL.5432]/test
  category: None
DRIVER: postgresql.driver.pq3.Driver
```

The code works with every other driver (psycopg2, pg8000, PyGreSQL.) When I run equivalent code directly with py-postgresql, it works:

```python
from postgresql.driver import dbapi20

con = dbapi20.connect(database="test")
cur = con.cursor()

cur.execute("""
CREATE TABLE person (
    id SERIAL PRIMARY KEY,
    name TEXT
)
""")

cur.execute("INSERT INTO person (name) VALUES ('Test') RETURNING id")
print(cur.fetchone()[0])  # => prints 1
```

Any idea what coud be wrong?

**Comment by jwp** [comment]
From the given information, this does not look like a py-postgresql issue. Are you using the latest version? Are there any downstream patches to py-postgresql's source that could have caused this? Is this connecting to a proxy like pgbouncer or pgpool? The driver tries to avoid doing anything interesting with the SQL strings that are fed to it aside from what is necessary to support DB-API's paramstyle which is not even at play here. Considering that we can see the rendered SQL string in the exception, it would appear to be valid syntax as well.

**Comment by phdru** [comment]
I [fixed](https://github.com/sqlobject/sqlobject/commit/f0311b04364b381df864352cc5a26328f297a9ab#diff-8aeb13c5c4341381813a158c6891040aR238) the problem by avoiding `RETURNING id` and instead `SELECTing` id from the sequence specially for py-postgresql. It works now. Still no idea what was causing the problem.

**Comment by phdru** [comment]
Happy New Year and thank you!
